// CIRQL — the world data model (CHR-217, CHR-218).
//
// CIRQL is the flagship: a persistent, magical, social world of concentric
// island-rings. This file is the *data* — ring/biome definitions + the props on
// each ring — kept declarative so new rings are added forever as config. The
// renderer (cirql-world-engine.ts) is generic and draws whatever these describe.
//
// Ring 0 = "The Hearth" (home). Outer rings are stubbed here and shown only on
// the minimap under fog until the community's sparks open them (Phase 2).

export type PropType =
  | "hearth"    // the home cottage (your Cirql lanterns ring it)
  | "wonders"   // the in-world arcade building (doorway → the 50 Wonders)
  | "npc"       // a quest-giver / townsperson
  | "tree"
  | "lantern"   // a plain path lantern
  | "crystal"
  | "dock"      // sail outward to another ring
  | "marker"    // a quest waypoint target
  | "tablet"    // a Myst-style clue stone (inspect → grants the puzzle + shows the clue)
  | "rune"      // a puzzle rune you toggle on/off
  | "shrine";   // sealed until the runes match the clue → opens for the reward

export interface Prop {
  t: PropType;
  x: number;
  y: number;
  id?: string;          // stable id (interaction targets, quest refs)
  label?: string;
  accent?: string;      // glow/label colour override
  to?: number;          // dock: destination ring index
  big?: boolean;        // larger tree/crystal
  r?: number;           // interaction/collision radius override (world units)
}

export interface RingPalette {
  sky: [string, string];
  sea: string;
  land: string;
  grass: string;
  sand: string;
  accent: string;       // biome signature (lanterns, UI)
  mote: string;         // floating-light colour
}

export interface Ring {
  index: number;
  name: string;
  sub: string;
  radius: number;       // island radius in world units
  explorable: boolean;
  palette: RingPalette;
  spawn: { x: number; y: number };
  props: Prop[];
  puzzleTarget?: string[];   // rune ids that must be lit (and no others) to open the shrine (CHR-258)
}

// ---- Ring 0: The Hearth -----------------------------------------------------
// Dusk purple/teal sky, warm sand, lantern gold — matching the approved lookbook.
const HEARTH: Ring = {
  index: 0,
  name: "The Hearth",
  sub: "your home ring",
  radius: 430,
  explorable: true,
  palette: {
    sky: ["#241640", "#12163a"],
    sea: "#0c2036",
    land: "#243a2f",
    grass: "#2f5340",
    sand: "#c9ad74",
    accent: "#ffc46b",
    mote: "#ffd98a",
  },
  spawn: { x: 0, y: 150 },
  props: [
    // home cottage — the Cirql lantern ring is generated by the engine around it
    { t: "hearth", x: 0, y: -70, id: "hearth", label: "The Hearth" },
    // CirqlCade — the in-world arcade (cosmic-roofed mystery building), east of home
    { t: "wonders", x: 250, y: 40, id: "wonders", label: "CirqlCade", accent: "#b26cff", r: 46 },
    // the Hearth-keeper NPC (first quest-giver), near spawn
    { t: "npc", x: -60, y: 120, id: "keeper", label: "Ferra", accent: "#7fffe6", r: 34 },
    // trees / scenery
    { t: "tree", x: 190, y: -220, big: true },
    { t: "tree", x: -230, y: -180 },
    { t: "tree", x: 330, y: -120, big: true },
    { t: "tree", x: -340, y: 120 },
    { t: "tree", x: 120, y: 250 },
    { t: "tree", x: -150, y: 280, big: true },
    { t: "tree", x: 300, y: 220 },
    // the path lanterns to the Wonders — quest targets for "The Lantern Path"
    { t: "lantern", x: 95, y: 75, id: "ql1" },
    { t: "lantern", x: 165, y: 55, id: "ql2" },
    { t: "lantern", x: 215, y: 35, id: "ql3" },
    // the south dock — sail outward (fogged for now)
    { t: "dock", x: 0, y: 400, to: 1, label: "the fog", id: "dock-s" },
    // quest waypoint target (Quest 1 "Find Your Feet")
    { t: "marker", x: -230, y: -20, id: "marker-shore", label: "" },
    // ---- The Sunken Runes: a hidden puzzle grove in the NW corner (CHR-258) ----
    { t: "tablet", x: -370, y: -190, id: "rune-tablet", label: "Runestone" },
    { t: "rune", x: -352, y: -262, id: "rn0" },
    { t: "rune", x: -320, y: -240, id: "rn1" },
    { t: "rune", x: -284, y: -240, id: "rn2" },
    { t: "rune", x: -252, y: -262, id: "rn3" },
    { t: "shrine", x: -302, y: -300, id: "rune-shrine", label: "Sealed Shrine" },
  ],
  // wake all but the second rune (rn1 stays dark)
  puzzleTarget: ["rn0", "rn2", "rn3"],
};

// ---- Outer rings: stubbed (minimap-only until Phase 2 opens them) ------------
const OUTER: Ring[] = [
  { index: 1, name: "Whisperwood", sub: "beyond the fog", radius: 480, explorable: false,
    palette: HEARTH.palette, spawn: { x: 0, y: 0 }, props: [] },
  { index: 2, name: "Glimmer Bazaar", sub: "beyond the fog", radius: 460, explorable: false,
    palette: HEARTH.palette, spawn: { x: 0, y: 0 }, props: [] },
];

export const RINGS: Ring[] = [HEARTH, ...OUTER];

// How many concentric rings the minimap draws (sells "the world never ends").
export const MINIMAP_RINGS = 8;
// How many are currently "known" (bright); the rest are fog. Grows in Phase 2.
export const KNOWN_RINGS = 1;
