// Cirql Link — engine (CirqlArcade). Flow Free, wrapped onto a circle. Connect each
// pair of matching nodes with a path along the polar grid; paths can't cross.
// Solve the board and a new one appears. Beat the clock. Relaxing but tricky.
//
// Puzzles are generated by carving non-overlapping paths first, then exposing only
// their endpoints — so a non-crossing solution is always guaranteed to exist.

import { ArcadeEngine, type ArcadeOpts, TAU, LS } from "./arcade-core";

export interface LinkHud { solved: number; best: number; time: number; linked: number; pairs: number; }
export interface LinkResult { solved: number; best: number; }
export interface LinkOpts extends ArcadeOpts { accent?: string; onHud?: (s: LinkHud) => void; onRunEnd?: (r: LinkResult) => void; }

type Flow = "menu" | "playing" | "over";
const RINGS = 4, SEG = 8, SEG_A = TAU / SEG, RUN_TIME = 75;
const COLORS = ["#f472b6", "#38bdf8", "#34d399", "#fbbf24", "#a78bfa"];

export class LinkEngine extends ArcadeEngine {
  private opts: LinkOpts;
  private accent = "#38bdf8";
  private flow: Flow = "menu";
  private solved = 0; private best = +(LS.get("clink_best") || 0);
  private nodes: [number, number][] = [];     // per color: [cellA, cellB]
  private committed = new Map<number, number[]>(); // color → path cells
  private active: { color: number; path: number[] } | null = null;
  private timeLeft = RUN_TIME; private lastHud = "";

  constructor(canvas: HTMLCanvasElement, opts: LinkOpts = {}) { super(canvas, opts); if (opts.accent) this.accent = opts.accent; this.opts = opts; this.emitHud(); }

  private cell(r: number, c: number) { return r * SEG + ((c % SEG) + SEG) % SEG; }
  private rc(cell: number): [number, number] { return [Math.floor(cell / SEG), cell % SEG]; }
  private ringR(r: number) { return this.rimR * (0.3 + 0.6 * (r / (RINGS - 1))); }
  private neighbors(cell: number): number[] { const [r, c] = this.rc(cell); const out = [this.cell(r, c + 1), this.cell(r, c - 1)]; if (r > 0) out.push(this.cell(r - 1, c)); if (r < RINGS - 1) out.push(this.cell(r + 1, c)); return out; }
  private cellXY(cell: number) { const [r, c] = this.rc(cell); const a = c * SEG_A, rr = this.ringR(r); return { x: this.cx + Math.cos(a) * rr, y: this.cy + Math.sin(a) * rr }; }

  start() { this.flow = "playing"; this.solved = 0; this.timeLeft = RUN_TIME; this.generate(); this.emitHud(); }
  toMenu() { this.flow = "menu"; this.nodes = []; this.committed.clear(); this.active = null; this.clearFx(); }
  peekBest() { return this.best; }

  private generate() {
    const P = Math.min(COLORS.length, 3 + Math.floor(this.solved / 2));
    for (let attempt = 0; attempt < 12; attempt++) {
      const reserved = new Set<number>(); const nodes: [number, number][] = []; let ok = true;
      for (let p = 0; p < P; p++) {
        // random walk from a free cell
        const frees = []; for (let i = 0; i < RINGS * SEG; i++) if (!reserved.has(i)) frees.push(i);
        if (!frees.length) { ok = false; break; }
        let cur = frees[Math.floor(Math.random() * frees.length)];
        const path = [cur]; const used = new Set([cur]);
        const steps = 2 + Math.floor(Math.random() * 4);
        for (let s = 0; s < steps; s++) { const opts = this.neighbors(cur).filter((n) => !reserved.has(n) && !used.has(n)); if (!opts.length) break; cur = opts[Math.floor(Math.random() * opts.length)]; path.push(cur); used.add(cur); }
        if (path.length < 2) { ok = false; break; }
        path.forEach((c) => reserved.add(c)); nodes.push([path[0], path[path.length - 1]]);
      }
      if (ok && nodes.length === P) { this.nodes = nodes; this.committed.clear(); this.active = null; return; }
    }
    // fallback: two simple radial pairs
    this.nodes = [[this.cell(0, 0), this.cell(RINGS - 1, 0)], [this.cell(0, 4), this.cell(RINGS - 1, 4)]]; this.committed.clear(); this.active = null;
  }

  private occ(): Map<number, number> { const m = new Map<number, number>(); for (const [color, path] of Array.from(this.committed.entries())) for (const c of path) m.set(c, color); return m; }
  private nodeColorAt(cell: number): number { for (let i = 0; i < this.nodes.length; i++) if (this.nodes[i][0] === cell || this.nodes[i][1] === cell) return i; return -1; }
  private cellAt(x: number, y: number): number | null {
    let best = -1, bd = this.rimR * 0.13;
    for (let i = 0; i < RINGS * SEG; i++) { const p = this.cellXY(i); const d = Math.hypot(p.x - x, p.y - y); if (d < bd) { bd = d; best = i; } }
    return best < 0 ? null : best;
  }

  protected onPointerDown(e: PointerEvent) {
    if (this.flow !== "playing") return; const cell = this.cellAt(this.pointerPos(e).x, this.pointerPos(e).y); if (cell == null) return;
    const color = this.nodeColorAt(cell);
    if (color < 0) return; // must start on a node
    this.committed.delete(color); // redo this color
    this.active = { color, path: [cell] };
    this.tone(300, 0.04, "sine", 0.03);
  }
  protected onPointerMove(e: PointerEvent) {
    if (!this.active) return; const cell = this.cellAt(this.pointerPos(e).x, this.pointerPos(e).y); if (cell == null) return;
    const path = this.active.path; const tail = path[path.length - 1];
    if (cell === tail) return;
    const bi = path.indexOf(cell); if (bi >= 0) { path.length = bi + 1; return; } // backtrack
    if (!this.neighbors(tail).includes(cell)) return; // must be adjacent
    const occ = this.occ(); if (occ.has(cell) && occ.get(cell) !== this.active.color) return; // blocked by another
    const nc = this.nodeColorAt(cell); if (nc >= 0 && nc !== this.active.color) return; // can't cross other node
    path.push(cell);
    // reached the matching pair node?
    const [a, b] = this.nodes[this.active.color];
    if ((cell === a || cell === b) && cell !== path[0]) { this.commit(); }
  }
  protected onPointerUp() { if (this.active) { this.active = null; } }

  private commit() {
    if (!this.active) return;
    this.committed.set(this.active.color, this.active.path.slice());
    const end = this.cellXY(this.active.path[this.active.path.length - 1]);
    this.burst(end.x, end.y, COLORS[this.active.color], 8, this.rimR * 0.6); this.tone(560, 0.1, "triangle", 0.045); this.buzz(6);
    this.active = null;
    if (this.committed.size === this.nodes.length) { this.solved++; this.tone(880, 0.25, "sine", 0.05); this.buzz([10, 20, 10]); this.shock(this.cx, this.cy, this.accent, this.rimR); this.pop(this.cx, this.cy, "SOLVED", "#34d399"); this.generate(); }
    this.emitHud();
  }

  protected step(dt: number, _now: number) { if (this.flow !== "playing") return; this.timeLeft -= dt; if (this.timeLeft <= 0) { this.timeLeft = 0; this.gameOver(); } this.emitHud(); }
  private gameOver() { this.flow = "over"; this.best = Math.max(this.best, this.solved); LS.set("clink_best", String(this.best)); [330, 262, 196].forEach((f, i) => setTimeout(() => this.tone(f, 0.4, "sine", 0.05), i * 120)); this.opts.onRunEnd?.({ solved: this.solved, best: this.best }); this.emitHud(); }

  private emitHud() { if (!this.opts.onHud) return; const sig = [this.solved, Math.ceil(this.timeLeft), this.committed.size].join("|"); if (sig === this.lastHud) return; this.lastHud = sig; this.opts.onHud({ solved: this.solved, best: this.best, time: Math.ceil(this.timeLeft), linked: this.committed.size, pairs: this.nodes.length }); }

  protected draw(now: number) {
    const { ctx, cx, cy, rimR } = this;
    const g = ctx.createRadialGradient(cx, cy, 0, cx, cy, rimR * 1.15); g.addColorStop(0, "rgba(56,189,248,.06)"); g.addColorStop(1, "rgba(5,4,15,0)");
    ctx.fillStyle = g; ctx.beginPath(); ctx.arc(cx, cy, rimR * 1.15, 0, TAU); ctx.fill();
    // grid dots
    for (let i = 0; i < RINGS * SEG; i++) { const p = this.cellXY(i); ctx.fillStyle = "rgba(150,130,255,.14)"; ctx.beginPath(); ctx.arc(p.x, p.y, 2, 0, TAU); ctx.fill(); }
    // committed paths + active
    const drawPath = (path: number[], color: string, alpha: number) => { if (path.length < 2) return; ctx.save(); ctx.globalAlpha = alpha; ctx.strokeStyle = color; ctx.lineWidth = rimR * 0.05; ctx.lineCap = "round"; ctx.lineJoin = "round"; ctx.shadowBlur = 10; ctx.shadowColor = color; ctx.beginPath(); const p0 = this.cellXY(path[0]); ctx.moveTo(p0.x, p0.y); for (let i = 1; i < path.length; i++) { const p = this.cellXY(path[i]); ctx.lineTo(p.x, p.y); } ctx.stroke(); ctx.restore(); ctx.globalAlpha = 1; };
    for (const [color, path] of Array.from(this.committed.entries())) drawPath(path, COLORS[color], 0.85);
    if (this.active) drawPath(this.active.path, COLORS[this.active.color], 0.6);
    // nodes
    for (let i = 0; i < this.nodes.length; i++) for (const cell of this.nodes[i]) { const p = this.cellXY(cell); ctx.save(); ctx.shadowBlur = 12; ctx.shadowColor = COLORS[i]; ctx.fillStyle = COLORS[i]; ctx.beginPath(); ctx.arc(p.x, p.y, rimR * 0.035, 0, TAU); ctx.fill(); ctx.restore(); }
    this.drawFx(now); void now;
  }
}
